Add arch to exported os methods
I'm using a library which depends on package `xhr2` and was getting an error 
```
Uncaught TypeError: os.arch is not a function
```
which was getting invoked here, https://github.com/pwnall/node-xhr2/blob/4a2c826f60342501dc51e708882748840ba5dc6b/src/001-xml_http_request.coffee#L395